# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05d7cc5857488feaaa33fdb6f7b668d1aef07777ae39de48fb1f4682e1ea284168054ec3f9da75bacac9b6a9baeb000c5e9a17a100059b9ea82c25e9344a278d

test:
  secret_key_base: 59382a22d6b670e2187417463efb8ab0fd79cc9cbed85e49fb0cee1d7c7aad4ea0dcaa16e85f8a4628b6c16000ea7f77733b13c00cd4b456ca4e91d2718dd172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
